# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20170924_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resources.EntityCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resources.PropertyCategory'),
            preserve_default=False,
        ),
    ]
