# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20170924_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.EntityCategory'),
        ),
    ]
