# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20170930_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entitytopropertyrelation',
            old_name='_property',
            new_name='property',
        ),
        migrations.RenameField(
            model_name='propertytopersonrelation',
            old_name='_property',
            new_name='property',
        ),
    ]
