# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ActionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ActionToResultRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.Action')),
            ],
        ),
        migrations.CreateModel(
            name='ActionToResultRelationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PlanCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlanToActionRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.Action')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='PlanToActionRelationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ResultCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResultToPlanRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='ResultToPlanRelationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='resulttoplanrelation',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.ResultToPlanRelationCategory'),
        ),
        migrations.AddField(
            model_name='resulttoplanrelation',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.Result'),
        ),
        migrations.AddField(
            model_name='result',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.ResultCategory'),
        ),
        migrations.AddField(
            model_name='plantoactionrelation',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.PlanToActionRelationCategory'),
        ),
        migrations.AddField(
            model_name='plan',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.PlanCategory'),
        ),
        migrations.AddField(
            model_name='actiontoresultrelation',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.ActionToResultRelationCategory'),
        ),
        migrations.AddField(
            model_name='actiontoresultrelation',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.Result'),
        ),
        migrations.AddField(
            model_name='action',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.ActionCategory'),
        ),
    ]
