# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persontoentityrelation',
            old_name='function',
            new_name='relation',
        ),
    ]
