# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 22:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_database', '0002_auto_20170705_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='isuser',
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
