# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_database', '0002_auto_20170914_2300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonfunctionCategory',
            new_name='PersonToEntityRelationCategory',
        ),
    ]
