# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_database', '0005_auto_20170923_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyToPersonRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_database.Property')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_database.Person')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_database.PropertyToPersonRelationCategory')),
            ],
        ),
    ]
