# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 17:14
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_created', models.DateTimeField(default=datetime.datetime(2017, 9, 23, 17, 14, 3, 340668, tzinfo=utc))),
                ('case_ended', models.DateTimeField(blank=True, null=True)),
                ('case_createdBy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
