# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 18:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('process_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 23, 18, 22, 9, 586993, tzinfo=utc)),
        ),
    ]
