# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process_control', '0002_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='case_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='process_control.Case'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjecttoentityrelation',
            name='case_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='process_control.Case'),
            preserve_default=False,
        ),
    ]
