# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 19:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('process_control', '0003_auto_20170913_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 18, 19, 24, 34, 787084, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_createdBy',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
