# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 18:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('process_control', '0006_auto_20170923_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 24, 18, 25, 27, 117377, tzinfo=utc)),
        ),
    ]
