# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 15:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_manager', '0005_auto_20170923_1738'),
        ('process_control', '0008_auto_20170923_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='case_number',
        ),
        migrations.RemoveField(
            model_name='subjecttoentityrelation',
            name='case_number',
        ),
        migrations.RemoveField(
            model_name='subjecttoentityrelation',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='subjecttoentityrelation',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='subjecttoentityrelation',
            name='subject',
        ),
        migrations.AlterField(
            model_name='case',
            name='case_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 23, 15, 38, 35, 12395, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='SubjectToEntityRelation',
        ),
        migrations.DeleteModel(
            name='SubjectToEntityRelationCategory',
        ),
    ]
