# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_auto_20170924_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='executive_entity',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='executive_entity',
        ),
        migrations.RemoveField(
            model_name='result',
            name='executive_entity',
        ),
        migrations.AddField(
            model_name='action',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='result',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
