# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_plan_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actiontoresultrelation',
            old_name='relation',
            new_name='relation_category',
        ),
        migrations.RenameField(
            model_name='plantoactionrelation',
            old_name='relation',
            new_name='relation_category',
        ),
        migrations.RenameField(
            model_name='resulttoplanrelation',
            old_name='relation',
            new_name='relation_category',
        ),
    ]
