# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 19:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('process_control', '0007_auto_20170924_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 24, 19, 10, 0, 764499, tzinfo=utc)),
        ),
    ]
