# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_meetdate', models.DateField(blank=True, null=True)),
                ('meetingrequest_sent', models.DateTimeField(blank=True, null=True)),
                ('meeting_started', models.DateTimeField(blank=True, null=True)),
                ('meeting_completed', models.DateTimeField(blank=True, null=True)),
                ('report_started', models.DateTimeField(blank=True, null=True)),
                ('report_completed', models.DateTimeField(blank=True, null=True)),
                ('is_current_meeting', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_database.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_headline', models.CharField(blank=True, max_length=300)),
                ('edited_description', models.TextField(blank=True)),
                ('listposition_on_request', models.IntegerField(blank=True, null=True)),
                ('listposition_on_report', models.IntegerField(blank=True, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting_manager.Meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_meetingrequest', models.BooleanField(default=False)),
                ('is_invited', models.BooleanField(default=False)),
                ('accepted_invite', models.DateTimeField(blank=True, null=True)),
                ('is_attending', models.BooleanField(default=False)),
                ('is_leading', models.BooleanField(default=False)),
                ('is_reporting', models.BooleanField(default=False)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting_manager.Meeting')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_database.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='meetingsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting_manager.Subject'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting_manager.MeetingCategory'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_subjects',
            field=models.ManyToManyField(through='meeting_manager.MeetingSubject', to='meeting_manager.Subject'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(through='meeting_manager.Participant', to='core_database.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set([('meeting', 'person')]),
        ),
        migrations.AlterUniqueTogether(
            name='meetingsubject',
            unique_together=set([('meeting', 'subject')]),
        ),
    ]
