# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
        ('meeting_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='entity',
            new_name='executive_entity',
        ),
        migrations.RenameField(
            model_name='meetingsubject',
            old_name='plan',
            new_name='plan_item',
        ),
        migrations.AlterUniqueTogether(
            name='meetingsubject',
            unique_together=set([('meeting', 'listposition_on_report'), ('meeting', 'listposition_on_request'), ('meeting', 'plan_item')]),
        ),
    ]
