# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meetingrequest_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
