# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_database', '0004_auto_20170708_0148'),
        ('meeting_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core_database.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set([('meeting', 'person')]),
        ),
    ]
