# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_database', '0001_initial'),
        ('meeting_manager', '0002_auto_20170717_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectToEntityRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_database.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectToEntityRelationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='meetingsubject',
            options={'ordering': ('meeting', 'listposition_on_request')},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ('meeting', 'person__first_name')},
        ),
        migrations.AddField(
            model_name='subjecttoentityrelation',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting_manager.SubjectToEntityRelationCategory'),
        ),
        migrations.AddField(
            model_name='subjecttoentityrelation',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting_manager.Subject'),
        ),
    ]
