# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_manager', '0002_auto_20170712_0056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participant',
            new_name='MeetingParticipation',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_subjects',
            field=models.ManyToManyField(to='meeting_manager.MeetingSubject'),
        ),
    ]
