# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_manager', '0002_meeting_meetingrequest_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingsubject',
            old_name='edited_description',
            new_name='report_text',
        ),
        migrations.RenameField(
            model_name='meetingsubject',
            old_name='edited_headline',
            new_name='request_headline',
        ),
        migrations.AddField(
            model_name='meetingsubject',
            name='request_description',
            field=models.TextField(blank=True),
        ),
    ]
