# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_manager', '0003_auto_20170913_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingsubject',
            name='report_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meetingsubject',
            name='report_headline',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
