# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_manager', '0003_auto_20170712_0106'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeetingParticipation',
            new_name='Participant',
        ),
    ]
