# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_manager', '0004_auto_20170712_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_database.Person'),
        ),
    ]
