# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_database', '0006_propertytopersonrelation'),
        ('meeting_manager', '0004_auto_20170913_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectToEntityRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_database.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectToEntityRelationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='wrote_meetingreport',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_subjects',
            field=models.ManyToManyField(through='meeting_manager.MeetingSubject', to='meeting_manager.Subject'),
        ),
        migrations.AlterField(
            model_name='meetingsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting_manager.Subject'),
        ),
        migrations.AddField(
            model_name='subjecttoentityrelation',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting_manager.SubjectToEntityRelationCategory'),
        ),
        migrations.AddField(
            model_name='subjecttoentityrelation',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting_manager.Subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='entity_relation',
            field=models.ManyToManyField(through='meeting_manager.SubjectToEntityRelation', to='core_database.Entity'),
        ),
    ]
