# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_manager', '0005_auto_20170923_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescisionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
